// Code generated by gen/main.go; DO NOT EDIT.

package audio

const (
	destNone = iota
	destOsc0Volume
	destOsc1Volume
	destVibrato
	destTremolo
	destFM
	destPM
	destAM
	destFreq
	destNoteFilterFreq
	destNoteFilterQ
	destNoteFilterGain
	destFilterFreq
	destFilterQ
	destFilterGain
	destLfo0Freq
	destLfo1Freq
	destLfo2Freq
	destLfo0Amount
	destLfo1Amount
	destLfo2Amount
)

func destinationFromString(s string) int {
	switch s {
	case "none":
		return destNone
	case "osc0_volume":
		return destOsc0Volume
	case "osc1_volume":
		return destOsc1Volume
	case "vibrato":
		return destVibrato
	case "tremolo":
		return destTremolo
	case "fm":
		return destFM
	case "pm":
		return destPM
	case "am":
		return destAM
	case "freq":
		return destFreq
	case "note_filter_freq":
		return destNoteFilterFreq
	case "note_filter_q":
		return destNoteFilterQ
	case "note_filter_gain":
		return destNoteFilterGain
	case "filter_freq":
		return destFilterFreq
	case "filter_q":
		return destFilterQ
	case "filter_gain":
		return destFilterGain
	case "lfo0_freq":
		return destLfo0Freq
	case "lfo1_freq":
		return destLfo1Freq
	case "lfo2_freq":
		return destLfo2Freq
	case "lfo0_amount":
		return destLfo0Amount
	case "lfo1_amount":
		return destLfo1Amount
	case "lfo2_amount":
		return destLfo2Amount
	}
	return destNone
}
func destinationToString(d int) string {
	switch d {
	case destNone:
		return "none"
	case destOsc0Volume:
		return "osc0_volume"
	case destOsc1Volume:
		return "osc1_volume"
	case destVibrato:
		return "vibrato"
	case destTremolo:
		return "tremolo"
	case destFM:
		return "fm"
	case destPM:
		return "pm"
	case destAM:
		return "am"
	case destFreq:
		return "freq"
	case destNoteFilterFreq:
		return "note_filter_freq"
	case destNoteFilterQ:
		return "note_filter_q"
	case destNoteFilterGain:
		return "note_filter_gain"
	case destFilterFreq:
		return "filter_freq"
	case destFilterQ:
		return "filter_q"
	case destFilterGain:
		return "filter_gain"
	case destLfo0Freq:
		return "lfo0_freq"
	case destLfo1Freq:
		return "lfo1_freq"
	case destLfo2Freq:
		return "lfo2_freq"
	case destLfo0Amount:
		return "lfo0_amount"
	case destLfo1Amount:
		return "lfo1_amount"
	case destLfo2Amount:
		return "lfo2_amount"
	}
	return "none"
}
