// Code generated by gen/main.go; DO NOT EDIT.

package audio

const (
	envelopeKindComing = iota
	envelopeKindGoing
)

func envelopeKindFromString(s string) int {
	switch s {
	case "coming":
		return envelopeKindComing
	case "going":
		return envelopeKindGoing
	}
	return envelopeKindComing
}
func envelopeKindToString(d int) string {
	switch d {
	case envelopeKindComing:
		return "coming"
	case envelopeKindGoing:
		return "going"
	}
	return "coming"
}
