// Code generated by gen/main.go; DO NOT EDIT.

package audio

const (
	formantA = iota
	formantE
	formantI
	formantO
	formantU
)

func formantKindFromString(s string) int {
	switch s {
	case "a":
		return formantA
	case "e":
		return formantE
	case "i":
		return formantI
	case "o":
		return formantO
	case "u":
		return formantU
	}
	return formantA
}
func formantKindToString(d int) string {
	switch d {
	case formantA:
		return "a"
	case formantE:
		return "e"
	case formantI:
		return "i"
	case formantO:
		return "o"
	case formantU:
		return "u"
	}
	return "a"
}
