// Code generated by gen/main.go; DO NOT EDIT.

package audio

const (
	targetOscAll = iota
	targetOsc0
	targetOsc1
)

func targetOscFromString(s string) int {
	switch s {
	case "all":
		return targetOscAll
	case "0":
		return targetOsc0
	case "1":
		return targetOsc1
	}
	return targetOscAll
}
func targetOscToString(d int) string {
	switch d {
	case targetOscAll:
		return "all"
	case targetOsc0:
		return "0"
	case targetOsc1:
		return "1"
	}
	return "all"
}
