name: Test
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
      - run: sudo apt update
      - run: sudo apt install -y libasound2-dev
      - run: go install ./...
      - run: npm ci
      - run: npm run generate-code
      - run: npm run generate-wavetable
      - run: npm test
